### ISSUE TITLE
`cargo generate --git .` no longer works

### ISSUE THREAD

**Issue by fitzgen** [ashleygwilliams/cargo-generate#128]
This [broke the CI](https://travis-ci.org/rustwasm/wasm-pack-template/jobs/461137846#L871) for `rustwasm/wasm-pack-template`:

```
$ cargo generate --git . --name testing
 Creating project called `testing`...
warning: spurious network error (2 tries remaining): failed to resolve path 'file://./': No such file or directory; class=Os (2)
warning: spurious network error (1 tries remaining): failed to resolve path 'file://./': No such file or directory; class=Os (2)
error: failed to clone into: /home/travis/build/rustwasm/wasm-pack-template/testingTXqqxj
caused by: failed to resolve path 'file://./': No such file or directory; class=Os (2)
The command "cargo generate --git . --name testing" exited with 1.
```

-----------

### Steps to Reproduce

```
git clone https://github.com/rustwasm/wasm-pack-template.git
cd wasm-pack-template
cargo generate --git . --name testing
```

### Expected Results

Generates a `testing` project

### Actual Results

`cargo generate` does not exit successfully

**Comment by DD5HT** [comment]
The problem is in `git.rs` `GitConfig::new` does not like relative paths. It works with an absolute path. I can write a fix for this tomorrow @ashleygwilliams

**Comment by ashleygwilliams** [comment]
whoops, this why introduced by me when i merged the clone repos with cargo PR. i'm sorry! @DD5HT a PR would be awesome <3 thank you

**Comment by LandKingdom** [comment]
I thought this issue was the same I was having. Turns out I instead found a new one: if I prefix github with "www." i get the same error as in this issue (spurious network). I downloaded the source and modified it to just remove "www." if it was found. [Here](https://github.com/LandKingdom/cargo-generate/commit/affe3a16da4cd9ad22a5a61c718e38920baf16a4)'s the commit in question. I'm not making a PR solely because I haven't looked into fixing the relative path problem that @DD5HT is going to do anyway, so they might as well keep this in mind and maybe include it too.

**Comment by ashleygwilliams** [comment]
thank you @LandKingdom ! we'll be sure to fix this as well.

**Comment by DD5HT** [comment]
@LandKingdom @ashleygwilliams I'm gonna keep that in mind as well, I'm looking into an elegant solution to parse these urls, it's surprisingly not that easy. Also @LandKingdom removing www isn't maybe the best choice here. Since the url automatically redirects to the non www version anyway when normally used with git clone. So enabling redirection in cargo gen is maybe a better choice.

**Comment by LandKingdom** [comment]
I didn't really look into it, I just wanted to get it to work in my use case. I had already downloaded the code by the time I found it it was the "www." that had the problem, so I just fixed THAT and went on my way. I saw [Issue 67](https://github.com/ashleygwilliams/cargo-generate/issues/67) earlier, so you might want to also keep that in mind (since you mentioned that git clone redirects no problem)

**Comment by taurr** [comment]
Using redirects still doesn't work, but unfortunately that is a `git2`issue, not a `cargo-generate`one!

However, using 
```shell
cargo generate --git https://github.com/rustwasm/wasm-pack-template
```

the template in question works :-)
